---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3405633371-b6NWOtLIZv7yxEN1vSTmxCJb6s5H4XbWF27mF5S
:access_token_secret: 3sc3g5wuMyK1mNdcFa5N17HZ9OcT0esnxjvWBz87Ozn1b
